class News < ActiveRecord::Base
  # data ......................................................................
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  # validations ...............................................................
  # callbacks .................................................................
  before_save :filter_content

  # scopes ....................................................................
  scope :sort_order, -> { order("-sort desc, published_at desc, id desc") }

  # additional config .........................................................
  mount_uploader :cover, NewsCoverUploader

  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
  def filter_content
    filtered_content = ''
    content.each_char do |c|
      begin
        c.encode("GBK")
        filtered_content << c
      rescue
        filtered_content << "[表情]"
      end
    end
    self.content = filtered_content
  end
end
